<div class="finance_datum" >
                       <article><h2>[field:title/]</h2></article><br/>                                                    
                    <div class="condtext_datum">
                    <p style="background-color:#990000;font-size:19px;font-weight :bold;padding:10px 5px 13px 20px;width:715px; height:20px;color:#ffffff;">[field:description function="cn_substr(@me,8)"/]</p>
                    <p style="padding:10px 5px 10px 15px;line-height:25px; width:720px;font-size:13.5px;background-color:#f2f2f2;">
                        {dede:field.body/}
                    </p>
                    </div>
                </div>