<!--【1】-->
          <div class="polmain">
              <div class="poltitle"><article>[field:pubdate function="MyDate('<em>d</em><br/>Y-m',@me)"/] </article><a href="[field:arcurl/]"><h3>[field:title/]</h3></a></div>
              <div class="polart">
                  <p>[field:description function="cn_substr(@me,50000)"/]</p>
              </div>
              <div class="polzixun">
                  <a href="[field:arcurl/]"><em>查看更多</em></a>
              </div>
          </div>