
<field:demand itemname="请填写您的需求" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:demand>

<field:phone itemname="留下电话方便联系" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:name itemname="姓" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:source itemname="source" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:source>

<field:time itemname="time" autofield="1" type="datetime" isnull="true" default=""  maxlength="250" page="">
</field:time>


<field:ip itemname="ip" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ip>
