
<field:source itemname="source" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:source>

<field:time itemname="time" autofield="1" type="datetime" isnull="true" default=""  maxlength="250" page="">
</field:time>


<field:ip itemname="ip" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ip>

<field:name itemname="name" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>
