<!--【1】-->
          <div class="polmain">
              <div class="poltitle"><article><em>[field:pubdate function="MyDate('d',@me)"/]</em><br/>[field:pubdate function="MyDate('Y- m',@me)"/]</article><a href="[field:arcurl/]" target="_blank"><h3>[field:title/]</h3></a></div>
              <div class="polart">
                  <p>[field:description function="cn_substr(@me,50000)"/]</p>
              </div>
              <div class="polzixun">
                  <a href="[field:arcurl/]"><em>查看更多</em></a>
              </div>
          </div>