<?php
$z[0]=Array("global","",85,117);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",688,720);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",774,806);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",870,902);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",981,1013);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1084,1116);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1268,1300);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",2070,2102);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("include","",4976,5011);
$z[8][4]['filename']="head.htm";
$z[9]=Array("global","",7631,7663);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("list","\r\n                 <div class=\"finance_datum\" >\r\n                       <article><h2>[field:title/]</h2></article><br/>                                                    \r\n                    <div class=\"condtext_datum\">\r\n                    <p style=\"background-color:#990000;font-size:19px;font-weight :bold;padding:10px 5px 13px 20px;width:715px; height:20px;color:#ffffff;\">[field:shorttitle/]</p>\r\n                    <p style=\"padding:10px 5px 10px 15px;line-height:29px; width:720px;font-size:13.5px;background-color:#f2f2f2;\">\r\n                       [field:description function=\"cn_substr(@me,90000)\"/]\r\n                    </p>\r\n                    </div>\r\n                </div>\r\n                ",8803,9548);
$z[10][4]['pagesize']="4";
$z[11]=Array("include","",9660,9697);
$z[11][4]['filename']="footer.htm";

?>